# Generated by Django 4.0.6 on 2022-09-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComicBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover', models.URLField(blank=True)),
                ('number', models.IntegerField(blank=True)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('tag', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
