# Generated by Django 4.0.6 on 2022-08-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.URLField(blank=True)),
                ('isbn', models.CharField(blank=True, max_length=200)),
                ('keyword', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DecimalClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('k_isbn', models.CharField(blank=True, max_length=200)),
                ('kdc', models.CharField(blank=True, max_length=200)),
                ('ddc', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('edition', models.CharField(blank=True, max_length=200)),
                ('impression', models.CharField(blank=True, max_length=200)),
                ('binding', models.CharField(blank=True, max_length=200)),
                ('size', models.CharField(blank=True, max_length=200)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
