# Generated by Django 4.0.6 on 2022-09-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicbook',
            name='isbn',
        ),
        migrations.AlterField(
            model_name='comicbook',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
