# Generated by Django 4.0.6 on 2022-08-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_id', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('thumbnail', models.URLField(blank=True)),
                ('content', models.TextField(blank=True, max_length=2000)),
                ('published', models.DateField(blank=True)),
                ('keyword', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
