# Generated by Django 4.0.6 on 2022-09-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.URLField(blank=True)),
                ('content', models.TextField(blank=True, max_length=3000)),
                ('published', models.DateField(blank=True, null=True)),
                ('modified', models.DateField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
