# Generated by Django 4.0.6 on 2022-08-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.URLField(blank=True)),
                ('work', models.TextField(blank=True, max_length=1000)),
                ('history', models.TextField(blank=True, max_length=1000)),
                ('greeting', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
