# Generated by Django 4.0.6 on 2022-09-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovelWriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('penname', models.CharField(blank=True, max_length=50)),
                ('picture', models.URLField(blank=True)),
                ('birthday', models.CharField(blank=True, max_length=50)),
                ('birthplace', models.CharField(blank=True, max_length=50)),
                ('work', models.TextField(blank=True, max_length=1000)),
                ('history', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
